### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by danielzeller** [yongjhih/depth#1]
Hey.

Where did you attain this code? Reverse engineered the google play app? Please remove your this library ASAP to avoid confusion. Stealing code is not cool. If you don't remove it we will have to take legal action against you. 

This is the original project: https://github.com/danielzeller/Depth-LIB-Android-

Regards the developer of Depth LIB Daniel Zeller form Agens AS!

**Comment by yongjhih** [comment]
Oh, sorry, i did not found your open source project after you declared
open, so i just decompiled for gradle build with some modification about
research, it's not for stealing for what. Thanks for your notification,
I'll remove it.

2016-04-29 0:12 GMT+08:00 danielzeller notifications@github.com:

> Hey.
> 
> Where did you attain this code? Reverse engineered the google play app?
> Please remove your this library ASAP to avoid confusion. Stealing code is
> not cool. If you don't remove it we will have to take legal action against
> you.
> 
> This is the original project:
> https://github.com/danielzeller/Depth-LIB-Android-
> 
> Regards the developer of Depth LIB Daniel Zeller form Agens AS!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yongjhih/depth/issues/1

## 

Nicknames in internet: yongjhih, yjchen, andrew.chen, taiwandrew
Interestings: Vim, Linux, Debian, Drupal, Android.

Key fingerprint:
1024D/85EE7D38 E74A FD7A EECA 469B 5633  9523 976B 436E 85EE 7D38
4096R/01C54D62 3D32 9839 AE0E 0A9F 21CA  761C F5EE C1A8 01C5 4D62

**Comment by danielzeller** [comment]
Ok, good that you remove it, decompiling code that other people have made is not ok.

**Comment by yongjhih** [comment]
It's already forced updated that redirect to your open source project for stargazers and followers of this project.

Good job.

**Comment by danielzeller** [comment]
Thanks!
